### ISSUE TITLE
sensmon

### ISSUE THREAD

**Issue by roblad** [artekw/sensmon#1]
Bledy w instrukcji i plikach

pacman -Sy python2 python2-simplejson git screen remserial python2-pip 

wget http://lpccomp.bc.ca/remserial/remserial-1.4.tar.gz
tar -xvf remserial-1.4.tar.gz
cd remserial-1.4
make
sudo cp remserial /usr/bin
sudo cp remserial.o /usr/lib
sudo cp stty.o /usr/lib

wget https://bootstrap.pypa.io/get-pip.py
sudo python get-pip.py
wget https://bootstrap.pypa.io/ez_setup.py -O - | sudo python
sudo pip install redis
sudo pip install tornado 
sudo pip install tornado-redis
sudo pip install --alow-external pil qrcode

cd ~/
git clone https://github.com/artekw/sensmon.git
cd sensmon
sudo cp other/remserial.service /etc/systemd/system/remserial.service
sudo systemctl enable remserial.service
sudo systemctl start remserial.service

PS

remserial.service jest edytowany windowsem i ma ^M na koncach

sensmon.service ma sciezki pod ciebie a nie pod wszystkich, mozesz jakies zmienne zrobic $USER np i lokalizacja do ../other

**Comment by artekw** [comment]
spoko, to jest poprawione, tylko wrzucone na git. plik service w czasie
tworzenia ETA nie znane

W dniu 29 grudnia 2014 13:27 użytkownik roblad notifications@github.com
napisał:

> Bledy w instrukcji i plikach
> 
> pacman -Sy python2 python2-simplejson git screen remserial python2-pip
> 
> wget http://lpccomp.bc.ca/remserial/remserial-1.4.tar.gz
> tar -xvf remserial-1.4.tar.gz
> cd remserial-1.4
> make
> sudo cp remserial /usr/bin
> sudo cp remserial.o /usr/lib
> sudo cp stty.o /usr/lib
> 
> wget https://bootstrap.pypa.io/get-pip.py
> sudo python get-pip.py
> wget https://bootstrap.pypa.io/ez_setup.py -O - | sudo python
> sudo pip install redis
> sudo pip install tornado
> sudo pip install tornado-redis
> sudo pip install --alow-external pil qrcode
> 
> cd ~/
> git clone https://github.com/artekw/sensmon.git
> cd sensmon
> sudo cp other/remserial.service /etc/systemd/system/remserial.service
> sudo systemctl enable remserial.service
> sudo systemctl start remserial.service
> 
> PS
> 
> remserial.service jest edytowany windowsem i ma ^M na koncach
> 
> sensmon.service ma sciezki pod ciebie a nie pod wszystkich, mozesz jakies
> zmienne zrobic $USER np i lokalizacja do ../other
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/artekw/sensmon/issues/1.

## 

Pozdrawiam, Artur
Best regards, Artur
http://digi-led.pl / GG: 1518171 / Jabber: artekw@jabbim.pl
